# Generated by Django 3.1.2 on 2020-11-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lavajato', '0002_auto_20201101_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lavajato.cliente'),
            preserve_default=False,
        ),
    ]
